### ISSUE TITLE
Error with Newest Changes

### ISSUE THREAD

**Issue by ADRNALN** [Qbox-project/qbx-weathersync#8]
### Summary

When I load into my server utilizing the newest qbx-weathersync changes the error below appears

### Reproduction

![image](https://github.com/Qbox-project/qbx-weathersync/assets/32118783/063debed-85f8-4fb9-a713-f6fca4d47154)

### Expected behavior

Not error

### Actual behavior

Error lol

### Last Updated

today

### Custom Resources

N/A

### Resource Rename

I made necessary rename changes from qbx back to qb to not break compatibility with paid resources

**Comment by Manason** [comment]
Not that it's related to this bug but qbx-core should provide qb exports so shouldn't need a rename

**Comment by ADRNALN** [comment]
I should mention this started happening before the typo change that was just made a few minutes ago. Also thanks for that insight I will look to change back to qbx then!

**Comment by Manason** [comment]
> I should mention this started happening before the typo change that was just made a few minutes ago. Also thanks for that insight I will look to change back to qbx then!

It sounds like a core issue possibly. Do you know when it started happening?

**Comment by ADRNALN** [comment]
I updated qbx-weathersync yesterday and started noticing that issue

**Comment by ADRNALN** [comment]
With newest core changes and weathersync changes this is no longer an issue
